-- Bloque 1.1 — Semilla del catálogo global de SaaS (~513 filas)
-- Generado y curado a partir de conocimiento de productos reales; verified = true
-- (entradas curadas). Aliases incluyen variantes de extracto bancario/tarjeta
-- para alimentar el fuzzy matcher del bloque 1.3.

insert into public.saas_catalog (name, aliases, category, website, verified)
values
  ('15Five', array['15FIVE.COM', 'FIFTEEN FIVE'], 'hr', '15five.com', true),
  ('1Password', array['1PASSWORD.COM', 'AGILEBITS', 'AGILEBITS INC'], 'productivity', '1password.com', true),
  ('360Learning', array['360LEARNING.COM', '360LEARNING INC'], 'other', '360learning.com', true),
  ('8x8', array['8X8 INC', '8X8.COM'], 'communication', '8x8.com', true),
  ('ActiveCampaign', array['ACTIVECAMPAIGN LLC', 'AC*ACTIVECAMPAIGN'], 'marketing', 'activecampaign.com', true),
  ('Adobe Analytics', array['ADOBE *ANALYTICS', 'OMNITURE'], 'analytics', 'adobe.com', true),
  ('Adobe Creative Cloud', array['ADOBE *CREATIVE CLD', 'Creative Cloud', 'CC'], 'design', 'adobe.com', true),
  ('Adobe Illustrator', array['ADOBE *ILLUSTRATOR', 'AI'], 'design', 'adobe.com', true),
  ('Adobe InDesign', array['ADOBE *INDESIGN', 'ID'], 'design', 'adobe.com', true),
  ('Adobe Lightroom', array['ADOBE *LIGHTROOM', 'LR'], 'design', 'adobe.com', true),
  ('Adobe Photoshop', array['ADOBE *PHOTOSHOP', 'PS'], 'design', 'adobe.com', true),
  ('Adobe Sign', array['ADOBE *SIGN', 'ADOBE ACROSIGN'], 'sales', 'adobe.com', true),
  ('Adobe XD', array['ADOBE *XD', 'Adobe Experience Design', 'XD'], 'design', 'adobe.com', true),
  ('ADP', array['ADP PAYROLL', 'AUTOMATIC DATA PROC'], 'hr', 'adp.com', true),
  ('Affinity Designer', array['SERIF*AFFINITY'], 'design', 'affinity.serif.com', true),
  ('Agile CRM', array['AGILECRM.COM'], 'crm', 'agilecrm.com', true),
  ('Ahrefs', array['AHREFS PTE LTD', 'AHREFS.COM'], 'marketing', 'ahrefs.com', true),
  ('Airbase', array['AIRBASE.COM', 'AIRBASE INC'], 'finance', 'airbase.com', true),
  ('Airbyte', array['AIRBYTE INC', 'AIRBYTE.COM'], 'other', 'airbyte.com', true),
  ('Aircall', array['AIRCALL INC', 'AIRCALL.IO'], 'sales', 'aircall.io', true),
  ('Airtable', array['AIRTABLE.COM', 'FORMAGRID INC'], 'productivity', 'airtable.com', true),
  ('Algolia', array['ALGOLIA.COM', 'ALGOLIA INC'], 'devtools', 'algolia.com', true),
  ('Amplitude', array['AMPLITUDE.COM', 'AMPL ANALYTICS'], 'analytics', 'amplitude.com', true),
  ('Animoto', array['ANIMOTO INC', 'ANIMOTO.COM'], 'video', 'animoto.com', true),
  ('Any.do', array['ANYDO LTD'], 'productivity', 'any.do', true),
  ('Apollo.io', array['APOLLO IO INC'], 'sales', 'apollo.io', true),
  ('AppDynamics', array['CISCO*APPDYNAMICS', 'APPDYNAMICS.COM'], 'observability', 'appdynamics.com', true),
  ('Asana', array['ASANA.COM', 'ASANA INC'], 'productivity', 'asana.com', true),
  ('Attio', array['ATTIO.COM', 'ATTIO INC'], 'crm', 'attio.com', true),
  ('Auth0', array['AUTH0.COM', 'OKTA*AUTH0'], 'devtools', 'auth0.com', true),
  ('AWS', array['AWS EMEA', 'AMAZON WEB SERVICES'], 'devtools', 'aws.amazon.com', true),
  ('Axure RP', array['AXURE.COM', 'AXURE SOFTWARE'], 'design', 'axure.com', true),
  ('Backlog', array['NULAB INC', 'BACKLOG.COM'], 'project_management', 'backlog.com', true),
  ('Balsamiq', array['BALSAMIQ.COM', 'BALSAMIQ STUDIOS'], 'design', 'balsamiq.com', true),
  ('BambooHR', array['BAMBOOHR.COM', 'BAMBOO HR'], 'hr', 'bamboohr.com', true),
  ('Basecamp', array['BASECAMP.COM', '37SIGNALS'], 'productivity', 'basecamp.com', true),
  ('Better Stack', array['BETTERSTACK.COM', 'BETTER UPTIME'], 'observability', 'betterstack.com', true),
  ('BeyondTrust', array['BEYONDTRUST.COM', 'BEYONDTRUST INC'], 'security', 'beyondtrust.com', true),
  ('BigCommerce', array['BIGCOMMERCE.COM', 'BIGCOMMERCE INC'], 'other', 'bigcommerce.com', true),
  ('Bill.com', array['BILL.COM AP/AR', 'BILL PAYMENTS'], 'finance', 'bill.com', true),
  ('Bitbucket', array['ATLASSIAN*BITBUCKET', 'BITBUCKET.ORG'], 'devtools', 'bitbucket.org', true),
  ('Biteable', array['PADDLE.NET* BITEABLE', 'BITEABLE.COM'], 'video', 'biteable.com', true),
  ('Bitly', array['BITLY.COM', 'BITLY INC'], 'other', 'bitly.com', true),
  ('Bitrix24', array['BITRIX24.COM', 'BITRIX INC'], 'crm', 'bitrix24.com', true),
  ('Bitwarden', array['BITWARDEN INC', 'BITWARDEN.COM'], 'security', 'bitwarden.com', true),
  ('Blender', array['BLENDER FOUNDATION'], 'design', 'blender.org', true),
  ('BombBomb', array['BOMBBOMB LLC', 'BOMBBOMB.COM'], 'video', 'bombbomb.com', true),
  ('Bonusly', array['BONUSLY.COM', 'BONUS.LY'], 'hr', 'bonusly.com', true),
  ('Box', array['BOX.COM', 'BOX INC'], 'productivity', 'box.com', true),
  ('Braze', array['BRAZE INC', 'BRAZE.COM'], 'marketing', 'braze.com', true),
  ('Brevo', array['SENDINBLUE', 'BREVO.COM'], 'marketing', 'brevo.com', true),
  ('Brex', array['BREX.COM', 'BREX CARD'], 'finance', 'brex.com', true),
  ('Brightcove', array['BRIGHTCOVE INC', 'BRIGHTCOVE.COM'], 'video', 'brightcove.com', true),
  ('Buffer', array['BUFFER.COM', 'BUFFER INC'], 'marketing', 'buffer.com', true),
  ('Bugsnag', array['SMARTBEAR*BUGSNAG', 'BUGSNAG.COM'], 'observability', 'bugsnag.com', true),
  ('Buildkite', array['BUILDKITE.COM', 'BUILDKITE PTY'], 'devtools', 'buildkite.com', true),
  ('Calendly', array['CALENDLY LLC', 'CALENDLY.COM'], 'sales', 'calendly.com', true),
  ('Campaign Monitor', array['CAMPAIGN MONITOR PTY', 'CM*CAMPAIGNMONITOR'], 'marketing', 'campaignmonitor.com', true),
  ('Camtasia', array['TECHSMITH CORP'], 'video', 'techsmith.com', true),
  ('Canva', array['CANVA*PRO', 'CANVA PTY LTD', 'CANVA* SUBSCRIPTION', 'CANVA.COM'], 'marketing', 'canva.com', true),
  ('Capsule CRM', array['ZESTIA LTD', 'CAPSULECRM.COM'], 'crm', 'capsulecrm.com', true),
  ('CaptivateIQ', array['CAPTIVATEIQ INC', 'CIQ'], 'sales', 'captivateiq.com', true),
  ('Celoxis', array['CELOXIS.COM', 'CELOXIS TECH'], 'project_management', 'celoxis.com', true),
  ('Chanty', array['CHANTY.COM', 'CHANTY INC'], 'communication', 'chanty.com', true),
  ('Chargebee', array['CHARGEBEE.COM', 'CHARGEBEE INC'], 'finance', 'chargebee.com', true),
  ('Chartbeat', array['CHARTBEAT.COM'], 'analytics', 'chartbeat.com', true),
  ('Chartio', array['CHARTIO.COM'], 'analytics', 'chartio.com', true),
  ('Chatwoot', array['CHATWOOT INC', 'CHATWOOT.COM'], 'support', 'chatwoot.com', true),
  ('Checkly', array['CHECKLYHQ.COM', 'CHECKLY INC'], 'observability', 'checklyhq.com', true),
  ('Checkr', array['CHECKR.COM', 'CHECKR BACKGROUND'], 'hr', 'checkr.com', true),
  ('Chili Piper', array['CHILI PIPER INC', 'CHILIPIPER.COM'], 'sales', 'chilipiper.com', true),
  ('Chorus', array['CHORUS.AI', 'ZOOMINFO*CHORUS'], 'sales', 'chorus.ai', true),
  ('Chronosphere', array['CHRONOSPHERE.IO'], 'observability', 'chronosphere.io', true),
  ('CircleCI', array['CIRCLECI.COM', 'CIRCLECI INC'], 'devtools', 'circleci.com', true),
  ('Clari', array['CLARI INC', 'CLARI.COM'], 'sales', 'clari.com', true),
  ('Clay', array['CLAY.COM', 'CLAY.RUN'], 'sales', 'clay.com', true),
  ('Clearbit', array['CLEARBIT INC', 'HUBSPOT*CLEARBIT'], 'sales', 'clearbit.com', true),
  ('ClickUp', array['CLICKUP.COM', 'CLICKUP INC'], 'productivity', 'clickup.com', true),
  ('Clio', array['THEMIS SOLUTIONS', 'CLIO.COM'], 'other', 'clio.com', true),
  ('Clipchamp', array['MSFT * CLIPCHAMP', 'CLIPCHAMP.COM'], 'video', 'clipchamp.com', true),
  ('Close', array['CLOSE.COM', 'CLOSE.IO', 'ELASTIC INC'], 'crm', 'close.com', true),
  ('Cloudflare', array['CLOUDFLARE.COM', 'CLOUDFLARE INC'], 'devtools', 'cloudflare.com', true),
  ('Cloudinary', array['CLOUDINARY.COM', 'CLOUDINARY LTD'], 'other', 'cloudinary.com', true),
  ('Coda', array['CODA.IO', 'CODA PROJECT INC'], 'productivity', 'coda.io', true),
  ('Cognism', array['COGNISM LTD'], 'sales', 'cognism.com', true),
  ('Concord', array['CONCORDNOW.COM', 'CONCORD CLM'], 'other', 'concordnow.com', true),
  ('Confluence', array['ATLASSIAN*CONFLUENCE', 'ATLASSIAN'], 'productivity', 'atlassian.com', true),
  ('Constant Contact', array['CONSTANT CONTACT INC', 'CTCT*CONTACT'], 'marketing', 'constantcontact.com', true),
  ('ContractPodAi', array['CONTRACTPODAI.COM', 'CONTRACTPOD AI'], 'other', 'contractpodai.com', true),
  ('Copper', array['COPPER CRM', 'PROSPERWORKS'], 'crm', 'copper.com', true),
  ('Coralogix', array['CORALOGIX.COM'], 'observability', 'coralogix.com', true),
  ('CorelDRAW', array['COREL CORPORATION', 'COREL*CORELDRAW'], 'design', 'coreldraw.com', true),
  ('Countly', array['COUNTLY.COM', 'COUNT.LY'], 'analytics', 'countly.com', true),
  ('Coupa', array['COUPA.COM', 'COUPA SOFTWARE'], 'finance', 'coupa.com', true),
  ('Coursera for Business', array['COURSERA.ORG', 'COURSERA INC'], 'other', 'coursera.org', true),
  ('CoverWallet', array['COVERWALLET.COM', 'AON COVERWALLET'], 'other', 'coverwallet.com', true),
  ('Crazy Egg', array['CRAZYEGG.COM', 'CRAZYEGG HEATMAPS'], 'analytics', 'crazyegg.com', true),
  ('Creatio', array['CREATIO INC', 'BPMONLINE'], 'crm', 'creatio.com', true),
  ('Crisp', array['PADDLE.NET* CRISP', 'CRISP IM SAS', 'CRISP.CHAT'], 'support', 'crisp.chat', true),
  ('Crowdin', array['CROWDIN.COM', 'CROWDIN INC'], 'other', 'crowdin.com', true),
  ('CrowdStrike', array['CROWDSTRIKE.COM', 'CROWDSTRIKE INC'], 'security', 'crowdstrike.com', true),
  ('Crunchbase', array['CRUNCHBASE INC'], 'sales', 'crunchbase.com', true),
  ('Culture Amp', array['CULTUREAMP.COM', 'CULTURE AMP INC'], 'hr', 'cultureamp.com', true),
  ('CyberArk', array['CYBERARK.COM', 'CYBERARK SOFTWARE'], 'security', 'cyberark.com', true),
  ('Dacast', array['DACAST INC', 'DACAST.COM'], 'video', 'dacast.com', true),
  ('Darktrace', array['DARKTRACE.COM', 'DARKTRACE LTD'], 'security', 'darktrace.com', true),
  ('Dashlane', array['DASHLANE.COM', 'DASHLANE INC'], 'security', 'dashlane.com', true),
  ('Datadog', array['DATADOG.COM', 'DATADOG INC'], 'observability', 'datadoghq.com', true),
  ('Deel', array['DEEL.COM', 'DEEL INC'], 'hr', 'deel.com', true),
  ('Delinea', array['DELINEA.COM', 'THYCOTIC'], 'security', 'delinea.com', true),
  ('Deputy', array['DEPUTY.COM', 'DEPUTY APP'], 'hr', 'deputy.com', true),
  ('Descript', array['PADDLE.NET* DESCRIPT', 'DESCRIPT INC', 'DESCRIPT.COM'], 'video', 'descript.com', true),
  ('Detectify', array['DETECTIFY.COM', 'DETECTIFY AB'], 'security', 'detectify.com', true),
  ('Dialpad', array['DIALPAD.COM', 'DIALPAD INC'], 'communication', 'dialpad.com', true),
  ('DigitalOcean', array['DIGITALOCEAN.COM', 'DO'], 'devtools', 'digitalocean.com', true),
  ('Discord', array['DISCORD* NITRO', 'DISCORD INC'], 'communication', 'discord.com', true),
  ('Divvy', array['GETDIVVY.COM', 'BILL DIVVY'], 'finance', 'getdivvy.com', true),
  ('Docebo', array['DOCEBO INC', 'DOCEBO.COM'], 'other', 'docebo.com', true),
  ('Docker', array['DOCKER.COM', 'DOCKER HUB', 'DOCKER INC'], 'devtools', 'docker.com', true),
  ('DocSend', array['DROPBOX*DOCSEND', 'DOCSEND.COM'], 'other', 'docsend.com', true),
  ('DocuSign', array['DOCUSIGN INC', 'DOCUSIGN*ENVELOPE', 'DOCUSIGN.COM'], 'sales', 'docusign.com', true),
  ('Domo', array['DOMO.COM', 'DOMO INC'], 'analytics', 'domo.com', true),
  ('Drata', array['DRATA.COM', 'DRATA INC'], 'security', 'drata.com', true),
  ('Drift', array['DRIFT.COM', 'DRIFT COM INC'], 'communication', 'drift.com', true),
  ('Dropbox', array['DROPBOX*SUBSCRIPTION', 'DROPBOX.COM'], 'productivity', 'dropbox.com', true),
  ('Dropbox Sign', array['HELLOSIGN.COM', 'DROPBOX*SIGN'], 'sales', 'dropboxsign.com', true),
  ('Duo Security', array['CISCO*DUO', 'DUOSECURITY.COM'], 'security', 'duo.com', true),
  ('Dynatrace', array['DYNATRACE.COM', 'DYNATRACE LLC'], 'observability', 'dynatrace.com', true),
  ('EasyPost', array['EASYPOST.COM', 'EASYPOST INC'], 'other', 'easypost.com', true),
  ('Elastic Cloud', array['ELASTIC.CO', 'ELASTICSEARCH'], 'observability', 'elastic.co', true),
  ('Embroker', array['EMBROKER.COM', 'EMBROKER INC'], 'other', 'embroker.com', true),
  ('Envato Elements', array['ENVATO *ELEMENTS', 'ENVATO PTY LTD'], 'design', 'elements.envato.com', true),
  ('Envoy', array['ENVOY.COM', 'ENVOY INC'], 'other', 'envoy.com', true),
  ('Evernote', array['EVERNOTE CORP', 'EVERNOTE.COM'], 'productivity', 'evernote.com', true),
  ('Expensify', array['EXPENSIFY.COM', 'EXPENSIFY INC'], 'finance', 'expensify.com', true),
  ('Fastly', array['FASTLY.COM', 'FASTLY INC'], 'devtools', 'fastly.com', true),
  ('Favro', array['FAVRO AB', 'FAVRO.COM'], 'project_management', 'favro.com', true),
  ('FigJam', array['FIGMA *FIGJAM', 'FigJam Board'], 'design', 'figma.com', true),
  ('Figma', array['FIGMA INC', 'FIGMA.COM'], 'design', 'figma.com', true),
  ('Filmora', array['WONDERSHARE TECH'], 'video', 'filmora.wondershare.com', true),
  ('Firebase', array['GOOGLE *FIREBASE'], 'devtools', 'firebase.google.com', true),
  ('FireHydrant', array['FIREHYDRANT.COM', 'FIREHYDRANT INC'], 'observability', 'firehydrant.com', true),
  ('Fivetran', array['FIVETRAN.COM', 'FIVETRAN INC'], 'other', 'fivetran.com', true),
  ('Float', array['FLOAT.COM', 'FLOATSCHEDULE'], 'project_management', 'float.com', true),
  ('Flock', array['FLOCK.COM', 'FLOCK INC'], 'communication', 'flock.com', true),
  ('Flow', array['GETFLOW.COM', 'METALAB FLOW'], 'project_management', 'getflow.com', true),
  ('Folk', array['FOLK.APP', 'FOLK CRM'], 'crm', 'folk.app', true),
  ('Frame.io', array['ADOBE INC'], 'video', 'frame.io', true),
  ('Framer', array['FRAMER.COM', 'FRAMER B.V.'], 'design', 'framer.com', true),
  ('FreeAgent', array['FREEAGENT.COM'], 'finance', 'freeagent.com', true),
  ('Freedcamp', array['FREEDCAMP.COM'], 'project_management', 'freedcamp.com', true),
  ('FreshBooks', array['FRESHBOOKS.COM', 'FRESH BOOKS'], 'finance', 'freshbooks.com', true),
  ('Freshdesk', array['FRESHWORKS INC', 'FRESHDESK.COM', 'FD'], 'support', 'freshdesk.com', true),
  ('Freshsales', array['FRESHWORKS INC', 'FRESHSALES.IO', 'FRESHWORKS*FRESHSALES'], 'crm', 'freshsales.io', true),
  ('Freshservice', array['FRESHWORKS INC', 'FRESHSERVICE.COM'], 'support', 'freshservice.com', true),
  ('Front', array['FRONTAPP.COM', 'FRONT INC', 'FRONT APP INC'], 'communication', 'frontapp.com', true),
  ('FullStory', array['FULLSTORY.COM', 'FULLSTORY INC'], 'analytics', 'fullstory.com', true),
  ('Fyle', array['FYLEHQ.COM', 'FYLE EXPENSE'], 'finance', 'fylehq.com', true),
  ('GanttPRO', array['PADDLE.NET* GANTTPRO', 'GANTTPRO.COM'], 'project_management', 'ganttpro.com', true),
  ('GitGuardian', array['GITGUARDIAN.COM', 'GITGUARDIAN INC'], 'security', 'gitguardian.com', true),
  ('GitHub', array['GITHUB.COM', 'GH', 'GITHUB INC'], 'devtools', 'github.com', true),
  ('GitLab', array['GITLAB.COM', 'GITLAB INC', 'GL'], 'devtools', 'gitlab.com', true),
  ('Gladly', array['GLADLY INC', 'GLADLY.COM'], 'support', 'gladly.com', true),
  ('Gong', array['GONG.IO', 'GONG INC'], 'sales', 'gong.io', true),
  ('GoodDay', array['GOODDAY.WORK'], 'project_management', 'goodday.work', true),
  ('GoodTime', array['GOODTIME.IO', 'GOODTIME INC'], 'other', 'goodtime.io', true),
  ('Google Ads', array['GOOGLE*ADS', 'GOOGLE ADWORDS'], 'marketing', 'ads.google.com', true),
  ('Google Analytics', array['GOOGLE *ANALYTICS', 'GA4', 'GA'], 'marketing', 'analytics.google.com', true),
  ('Google Chat', array['GOOGLE *CHAT', 'GOOGLE WORKSPACE'], 'communication', 'google.com', true),
  ('Google Cloud Platform', array['GOOGLE *CLOUD', 'GCP'], 'devtools', 'cloud.google.com', true),
  ('Google Drive', array['GOOGLE *STORAGE', 'GOOGLE ONE'], 'productivity', 'google.com', true),
  ('Google Forms', array['GOOGLE *FORMS', 'GOOGLE.COM/FORMS'], 'other', 'forms.google.com', true),
  ('Google Meet', array['GOOGLE *MEET', 'GOOGLE WORKSPACE'], 'communication', 'google.com', true),
  ('Google Workspace', array['GOOGLE *GSUITE', 'GSuite'], 'productivity', 'workspace.google.com', true),
  ('Gorgias', array['GORGIAS INC', 'GORGIAS.COM'], 'support', 'gorgias.com', true),
  ('GoTo Meeting', array['GOTO*MEETING', 'GOTOMEETING'], 'communication', 'goto.com', true),
  ('Grafana Cloud', array['GRAFANA.COM', 'GRAFANA LABS'], 'observability', 'grafana.com', true),
  ('Grammarly', array['GRAMMARLY INC', 'GRAMMARLY.COM'], 'productivity', 'grammarly.com', true),
  ('Grasshopper', array['GRASSHOPPER.COM', 'GRASSHOPPER GROUP'], 'communication', 'grasshopper.com', true),
  ('Greenhouse', array['GREENHOUSE.IO', 'GREENHOUSE SOFTWARE'], 'hr', 'greenhouse.io', true),
  ('Groove', array['GROOVE.CO', 'GROOVE LABS', 'GROOVE HQ INC', 'GROOVEHQ.COM'], 'sales', 'groove.co', true),
  ('Guidde', array['PADDLE.NET* GUIDDE', 'GUIDDE.COM'], 'video', 'guidde.com', true),
  ('Gusto', array['GUSTO PAYROLL', 'GUSTO.COM'], 'hr', 'gusto.com', true),
  ('HappyFox', array['HAPPYFOX INC', 'HAPPYFOX.COM'], 'support', 'happyfox.com', true),
  ('Harvest', array['GETHARVEST.COM'], 'productivity', 'getharvest.com', true),
  ('HashiCorp Vault', array['HASHICORP*VAULT', 'VAULT'], 'security', 'vaultproject.io', true),
  ('Heap', array['HEAP.IO', 'HEAP ANALYTICS'], 'analytics', 'heap.io', true),
  ('Height', array['HEIGHT.APP', 'HEIGHT INC'], 'project_management', 'height.app', true),
  ('Help Scout', array['HELP SCOUT PBC', 'HELPSCOUT.COM'], 'support', 'helpscout.com', true),
  ('HelpCrunch', array['PADDLE.NET* HELPCRUNCH', 'HELPCRUNCH.COM'], 'support', 'helpcrunch.com', true),
  ('Helpshift', array['HELPSHIFT INC', 'HELPSHIFT.COM'], 'support', 'helpshift.com', true),
  ('Heroku', array['HEROKU.COM', 'SALESFORCE*HEROKU'], 'devtools', 'heroku.com', true),
  ('HiBob', array['HIBOB.COM', 'BOB HR'], 'hr', 'hibob.com', true),
  ('Highrise', array['HIGHRISEHQ.COM'], 'crm', 'highrisehq.com', true),
  ('Hive', array['HIVE TECHNOLOGY INC', 'HIVE.COM'], 'project_management', 'hive.com', true),
  ('Homebase', array['JOINHOMEBASE.COM', 'HOMEBASE HR'], 'hr', 'joinhomebase.com', true),
  ('Honeycomb', array['HONEYCOMB.IO', 'HOUND TECHNOLOGY INC'], 'observability', 'honeycomb.io', true),
  ('Hootsuite', array['HOOTSUITE INC', 'HOOTSUITE.COM'], 'marketing', 'hootsuite.com', true),
  ('Hotjar', array['HOTJAR LTD', 'HOTJAR.COM', 'PDDLE.NET* HOTJAR'], 'marketing', 'hotjar.com', true),
  ('HubSpot CRM', array['HUBSPOT INC', 'HUBSPOT.COM', 'HS CRM'], 'crm', 'hubspot.com', true),
  ('HubSpot Marketing Hub', array['HUBSPOT INC', 'HS MARKETING HUB'], 'marketing', 'hubspot.com', true),
  ('HubSpot Sales Hub', array['HUBSPOT INC', 'HS SALES HUB'], 'sales', 'hubspot.com', true),
  ('HubSpot Service Hub', array['HUBSPOT INC', 'HUBSPOT.COM'], 'support', 'hubspot.com', true),
  ('Icertis', array['ICERTIS.COM', 'ICERTIS INC'], 'other', 'icertis.com', true),
  ('iCloud', array['APPLE.COM/BILL', 'ICLOUD STORAGE'], 'productivity', 'icloud.com', true),
  ('Incident.io', '{}', 'observability', 'incident.io', true),
  ('Indicative', array['INDICATIVE.COM'], 'analytics', 'indicative.com', true),
  ('Insightly', array['INSIGHTLY INC', 'INSIGHTLY.COM'], 'crm', 'insightly.com', true),
  ('Instana', array['IBM*INSTANA', 'INSTANA.COM'], 'observability', 'instana.com', true),
  ('Intercom', array['INTERCOM.COM', 'INTERCOM INC'], 'communication', 'intercom.com', true),
  ('InVideo', array['FS *INVIDEO', 'INVIDEO.IO'], 'video', 'invideo.io', true),
  ('InVision', array['INVISIONAPP.COM', 'InVision App'], 'design', 'invisionapp.com', true),
  ('Ironclad', array['IRONCLAD INC', 'IRONCLADAPP.COM'], 'other', 'ironcladapp.com', true),
  ('Iterable', array['ITERABLE INC', 'ITERABLE.COM'], 'marketing', 'iterable.com', true),
  ('JazzHR', array['JAZZHR.COM', 'JAZZ HR'], 'hr', 'jazzhr.com', true),
  ('Jenkins', array['JENKINS CI'], 'devtools', 'jenkins.io', true),
  ('Jira', array['ATLASSIAN*JIRA', 'JIRA SOFTWARE'], 'productivity', 'atlassian.com', true),
  ('Jotform', array['JOTFORM.COM', 'JOTFORM INC', 'PADDLE.NET* JOTFORM'], 'other', 'jotform.com', true),
  ('JumpCloud', array['JUMPCLOUD.COM', 'JUMPCLOUD INC'], 'security', 'jumpcloud.com', true),
  ('June', array['JUNE.SO', 'ENJOY THE VUE JUNE'], 'analytics', 'june.so', true),
  ('Justworks', array['JUSTWORKS.COM', 'JUSTWORKS PEO'], 'hr', 'justworks.com', true),
  ('Kaltura', array['KALTURA INC', 'KALTURA.COM'], 'video', 'kaltura.com', true),
  ('Kanbanize', array['KANBANIZE.COM', 'BUSINESSMAP KANBANIZE'], 'project_management', 'kanbanize.com', true),
  ('Kapture CX', array['KAPTURECRM.COM', 'ADVERO KAPTURE'], 'support', 'kapturecrm.com', true),
  ('Kapwing', array['PADDLE.NET* KAPWING', 'KAPWING.COM'], 'video', 'kapwing.com', true),
  ('Kayako', array['KAYAKO LTD', 'KAYAKO.COM'], 'support', 'kayako.com', true),
  ('Keap', array['KEAP.COM', 'INFUSIONSOFT'], 'crm', 'keap.com', true),
  ('Keeper Security', array['KEEPERSECURITY.COM', 'KEEPER SECURITY INC'], 'security', 'keepersecurity.com', true),
  ('Kissmetrics', array['KISSMETRICS.IO'], 'analytics', 'kissmetrics.io', true),
  ('Klaviyo', array['KLAVIYO INC', 'KLAVIYO.COM'], 'marketing', 'klaviyo.com', true),
  ('Klipfolio', array['KLIPFOLIO.COM'], 'analytics', 'klipfolio.com', true),
  ('KnowBe4', array['KNOWBE4.COM', 'KNOWBE4 INC'], 'security', 'knowbe4.com', true),
  ('Kustomer', array['KUSTOMER INC', 'KUSTOMER.COM'], 'support', 'kustomer.com', true),
  ('Lansweeper', array['LANSWEEPER.COM', 'LANSWEEPER NV'], 'other', 'lansweeper.com', true),
  ('LastPass', array['LASTPASS.COM', 'GOTO*LASTPASS'], 'productivity', 'lastpass.com', true),
  ('Lattice', array['LATTICE.COM', 'LATTICE HR'], 'hr', 'lattice.com', true),
  ('LaunchDarkly', array['LAUNCHDARKLY.COM', 'LD'], 'devtools', 'launchdarkly.com', true),
  ('LegalZoom', array['LEGALZOOM.COM', 'LEGALZOOM INC'], 'other', 'legalzoom.com', true),
  ('Less Annoying CRM', array['LACRM', 'LESSANNOYINGCRM.COM'], 'crm', 'lessannoyingcrm.com', true),
  ('Lessonly', array['SEISMIC LESSONLY', 'LESSONLY.COM'], 'other', 'lessonly.com', true),
  ('Lever', array['LEVER.CO', 'LEVER TRM'], 'hr', 'lever.co', true),
  ('Lightstep', array['SERVICENOW*LIGHTSTEP'], 'observability', 'lightstep.com', true),
  ('Linear', array['LINEAR.APP', 'LINEAR ORBIT INC'], 'devtools', 'linear.app', true),
  ('Linearity Curve', array['LINEARITY.IO', 'VECTORNATOR'], 'design', 'linearity.io', true),
  ('LinkedIn Sales Navigator', array['LINKEDIN *SALES NAV', 'LNKD*SALESNAV', 'SALES NAV'], 'sales', 'linkedin.com', true),
  ('LinkSquares', array['LINKSQUARES.COM', 'LINKSQUARES INC'], 'other', 'linksquares.com', true),
  ('LiveAgent', array['QUALITY UNIT LLC', 'LIVEAGENT.COM'], 'support', 'liveagent.com', true),
  ('LiveChat', array['LIVECHAT SOFTWARE SA', 'LIVECHAT.COM'], 'support', 'livechat.com', true),
  ('Loggly', array['SOLARWINDS*LOGGLY'], 'observability', 'loggly.com', true),
  ('LogRocket', array['LOGROCKET.COM', 'LOGROCKET INC'], 'observability', 'logrocket.com', true),
  ('Lokalise', array['LOKALISE.COM', 'LOKALISE INC', 'PADDLE.NET* LOKALISE'], 'other', 'lokalise.com', true),
  ('Looker', array['GOOGLE *LOOKER', 'LOOKER.COM'], 'analytics', 'looker.com', true),
  ('Looker Studio', array['GOOGLE *DATA STUDIO', 'DATA STUDIO'], 'analytics', 'lookerstudio.google.com', true),
  ('Loom', array['PDDLE.NET* LOOM', 'LOOM.COM'], 'communication', 'loom.com', true),
  ('Lottiefiles', array['LOTTIEFILES.COM'], 'design', 'lottiefiles.com', true),
  ('Lusha', array['LUSHA LTD', 'LUSHA.COM'], 'sales', 'lusha.com', true),
  ('Magento', array['MAGENTO.COM', 'ADOBE*MAGENTO'], 'other', 'magento.com', true),
  ('Mailchimp', array['INTUIT MAILCHIMP', 'MAILCHIMP.COM', 'MC*MAILCHIMP'], 'marketing', 'mailchimp.com', true),
  ('Make', array['MAKE.COM', 'CELONIS MAKE', 'PADDLE.NET* MAKE'], 'other', 'make.com', true),
  ('ManageEngine ServiceDesk Plus', array['ZOHO*MANAGEENGINE', 'MANAGEENGINE.COM'], 'support', 'manageengine.com', true),
  ('Marketo', array['ADOBE *MARKETO', 'MARKETO INC'], 'marketing', 'marketo.com', true),
  ('Marvel', array['MARVELAPP.COM', 'Marvel App'], 'design', 'marvelapp.com', true),
  ('Matomo', array['MATOMO.ORG', 'PIWIK'], 'analytics', 'matomo.org', true),
  ('Mattermost', array['MATTERMOST.COM', 'MATTERMOST INC'], 'communication', 'mattermost.com', true),
  ('Maximizer CRM', array['MAXIMIZER.COM', 'MAXIMIZER SOFTWARE'], 'crm', 'maximizer.com', true),
  ('MeisterTask', array['MEISTERLABS*MEISTERTASK', 'MEISTERTASK.COM'], 'project_management', 'meistertask.com', true),
  ('Melio', array['MELIOPAYMENTS.COM', 'MELIO PAYMENTS'], 'finance', 'meliopayments.com', true),
  ('Membrain', array['MEMBRAIN.COM'], 'crm', 'membrain.com', true),
  ('Mercury', array['MERCURY.COM', 'MERCURY BANK'], 'finance', 'mercury.com', true),
  ('Meta Ads', array['FACEBK *ADS', 'META*ADS'], 'marketing', 'facebook.com', true),
  ('Metabase', array['METABASE.COM'], 'analytics', 'metabase.com', true),
  ('Microsoft 365', array['MSFT *E3', 'MSFT *365', 'O365'], 'productivity', 'microsoft.com', true),
  ('Microsoft Azure', array['MSFT *AZURE', 'MICROSOFT*AZURE', 'AZURE'], 'devtools', 'azure.microsoft.com', true),
  ('Microsoft Dynamics 365', array['MSFT *DYNAMICS', 'MICROSOFT*DYNAMICS 365', 'DYNAMICS CRM'], 'crm', 'dynamics.microsoft.com', true),
  ('Microsoft Project', array['MSFT *PROJECT', 'MICROSOFT*PROJECT'], 'project_management', 'microsoft.com', true),
  ('Microsoft Teams', array['MSFT *TEAMS'], 'communication', 'microsoft.com', true),
  ('Mimecast', array['MIMECAST.COM', 'MIMECAST NORTH AMERICA'], 'security', 'mimecast.com', true),
  ('Miro', array['MIRO.COM', 'REALTIME BOARD'], 'design', 'miro.com', true),
  ('Mixmax', array['MIXMAX INC', 'MIXMAX.COM'], 'sales', 'mixmax.com', true),
  ('Mixpanel', array['MIXPANEL.COM', 'MXPNL'], 'analytics', 'mixpanel.com', true),
  ('Mode Analytics', array['MODE.COM', 'MODE'], 'analytics', 'mode.com', true),
  ('monday CRM', array['MONDAY.COM', 'MNDY *MONDAY'], 'crm', 'monday.com', true),
  ('monday dev', array['MNDY *MONDAY DEV', 'MONDAY.COM'], 'project_management', 'monday.com', true),
  ('Monday.com', array['MONDAY COM LTD'], 'productivity', 'monday.com', true),
  ('MongoDB Atlas', array['MONGODB.COM', 'MONGODB INC'], 'devtools', 'mongodb.com', true),
  ('Moz', array['MOZ.COM', 'SEOMOZ'], 'marketing', 'moz.com', true),
  ('Mural', array['MURAL.CO', 'TANDEM MURAL'], 'other', 'mural.co', true),
  ('Mux', array['MUX INC', 'MUX.COM'], 'video', 'mux.com', true),
  ('n8n', array['N8N.IO', 'N8N GMBH'], 'other', 'n8n.io', true),
  ('Namely', array['NAMELY.COM', 'NAMELY INC'], 'hr', 'namely.com', true),
  ('Navan', array['NAVAN.COM', 'TRIPACTIONS'], 'finance', 'navan.com', true),
  ('Netlify', array['NETLIFY.COM', 'NETLIFY INC'], 'devtools', 'netlify.com', true),
  ('Netskope', array['NETSKOPE.COM', 'NETSKOPE INC'], 'security', 'netskope.com', true),
  ('NetSuite', array['ORACLE NETSUITE', 'NETSUITE.COM'], 'finance', 'netsuite.com', true),
  ('NetSuite CRM', array['ORACLE NETSUITE', 'NETSUITE INC'], 'crm', 'netsuite.com', true),
  ('New Relic', array['NEWRELIC.COM', 'NEW RELIC INC'], 'observability', 'newrelic.com', true),
  ('Next Insurance', array['NEXTINSURANCE.COM', 'NEXT INS US'], 'other', 'nextinsurance.com', true),
  ('Nextiva', array['NEXTIVA.COM', 'NEXTIVA INC'], 'communication', 'nextiva.com', true),
  ('Nimble', array['NIMBLE.COM', 'NIMBLE CRM'], 'crm', 'nimble.com', true),
  ('Notion', array['NOTION LABS INC', 'NOTION.SO'], 'productivity', 'notion.so', true),
  ('Noun Project', array['THENOUNPROJECT.COM'], 'design', 'thenounproject.com', true),
  ('npm', array['NPMJS.COM'], 'devtools', 'npmjs.com', true),
  ('nTask', array['PADDLE.NET* NTASK', 'NTASKMANAGER.COM'], 'project_management', 'ntaskmanager.com', true),
  ('Nutshell', array['NUTSHELL CRM', 'NUTSHELL.COM'], 'crm', 'nutshell.com', true),
  ('Odoo CRM', array['ODOO S.A.', 'ODOO.COM'], 'crm', 'odoo.com', true),
  ('OfficeSpace', array['OFFICESPACESOFTWARE.COM', 'OFFICESPACE SOFTWARE'], 'other', 'officespacesoftware.com', true),
  ('Officevibe', array['OFFICEVIBE.COM'], 'hr', 'officevibe.com', true),
  ('Okta', array['OKTA, INC.', 'OKTA INC'], 'security', 'okta.com', true),
  ('Olark', array['OLARK LLC', 'OLARK.COM'], 'support', 'olark.com', true),
  ('OmniPlan', array['THE OMNI GROUP', 'APPLE.COM/BILL'], 'project_management', 'omnigroup.com', true),
  ('OneDrive', array['MSFT *ONEDRIVE', 'MICROSOFT ONEDRIVE'], 'productivity', 'microsoft.com', true),
  ('OneLogin', array['ONE IDENTITY*ONELOGIN', 'ONELOGIN.COM'], 'security', 'onelogin.com', true),
  ('Ooma', array['OOMA INC', 'OOMA.COM'], 'communication', 'ooma.com', true),
  ('OpenPhone', array['OPENPHONE.COM', 'OPENPHONE INC'], 'communication', 'openphone.com', true),
  ('Opsgenie', array['ATLASSIAN*OPSGENIE'], 'observability', 'atlassian.com', true),
  ('OpsLevel', array['OPSLEVEL.COM', 'OPSLEVEL INC'], 'observability', 'opslevel.com', true),
  ('Optimizely', array['OPTIMIZELY INC', 'OPTIMIZELY.COM'], 'marketing', 'optimizely.com', true),
  ('Otter.ai', array['AISENSE INC'], 'productivity', 'otter.ai', true),
  ('Outlook', array['MSFT *OUTLOOK', 'MICROSOFT OUTLOOK'], 'communication', 'microsoft.com', true),
  ('Outreach', array['OUTREACH.IO', 'OUTREACH CORP'], 'sales', 'outreach.io', true),
  ('PagerDuty', array['PAGERDUTY.COM', 'PAGERDUTY INC'], 'observability', 'pagerduty.com', true),
  ('Palo Alto Networks', array['PALOALTONETWORKS.COM', 'PRISMA CLOUD'], 'security', 'paloaltonetworks.com', true),
  ('PandaDoc', array['PANDADOC INC', 'PANDADOC.COM'], 'sales', 'pandadoc.com', true),
  ('Panopto', array['PANOPTO INC', 'PANOPTO.COM'], 'video', 'panopto.com', true),
  ('Papertrail', array['SOLARWINDS*PAPERTRAIL'], 'observability', 'papertrailapp.com', true),
  ('Pardot', array['SALESFORCE*PARDOT', 'PARDOT.COM'], 'marketing', 'pardot.com', true),
  ('Paycom', array['PAYCOM.COM', 'PAYCOM PAYROLL'], 'hr', 'paycom.com', true),
  ('Paylocity', array['PAYLOCITY.COM', 'PAYLOCITY CORP'], 'hr', 'paylocity.com', true),
  ('Paymo', array['PADDLE.NET* PAYMO', 'PAYMOAPP.COM'], 'project_management', 'paymoapp.com', true),
  ('Payoneer', array['PAYONEER.COM', 'PAYONEER INC'], 'finance', 'payoneer.com', true),
  ('PayPal', array['PAYPAL *', 'PYPL'], 'finance', 'paypal.com', true),
  ('Pendo', array['PENDO.IO', 'PENDO ANALYTICS'], 'analytics', 'pendo.io', true),
  ('Personio', array['PERSONIO.COM', 'PERSONIO GMBH'], 'hr', 'personio.com', true),
  ('Phrase', array['PHRASE.COM', 'PHRASE GMBH'], 'other', 'phrase.com', true),
  ('Ping Identity', array['PINGIDENTITY.COM', 'PING IDENTITY CORP'], 'security', 'pingidentity.com', true),
  ('Pingdom', array['SOLARWINDS*PINGDOM'], 'observability', 'pingdom.com', true),
  ('Pipedrive', array['PIPEDRIVE.COM', 'PIPEDRIVE INC'], 'crm', 'pipedrive.com', true),
  ('Pirate Ship', array['PIRATESHIP.COM', 'PIRATE SHIP LLC'], 'other', 'pirateship.com', true),
  ('Pixelmator Pro', array['APPLE.COM/BILL', 'PIXELMATOR TEAM'], 'design', 'pixelmator.com', true),
  ('PlanetScale', array['PLANETSCALE.COM', 'PLANETSCALE INC'], 'devtools', 'planetscale.com', true),
  ('Pleo', array['PLEO.IO', 'PLEO CARD'], 'finance', 'pleo.io', true),
  ('Podio', array['CITRIX SYSTEMS', 'PODIO.COM'], 'project_management', 'podio.com', true),
  ('PostHog', array['POSTHOG.COM', 'PADDLE.NET* POSTHOG'], 'analytics', 'posthog.com', true),
  ('Postman', array['POSTMAN INC', 'GETPOSTMAN.COM'], 'devtools', 'postman.com', true),
  ('Power BI', array['MSFT *POWER BI', 'MICROSOFT*POWERBI', 'PBI'], 'analytics', 'powerbi.microsoft.com', true),
  ('Precoro', array['PRECORO.COM', 'PADDLE.NET* PRECORO'], 'other', 'precoro.com', true),
  ('Principle', array['PRINCIPLE FOR MAC'], 'design', 'principleformac.com', true),
  ('Procreate', array['APPLE.COM/BILL', 'SAVAGE INTERACTIVE'], 'design', 'procreate.com', true),
  ('Procurify', array['PROCURIFY.COM', 'PROCURIFY INC'], 'other', 'procurify.com', true),
  ('Productboard', array['PRODUCTBOARD INC', 'PRODUCTBOARD.COM'], 'project_management', 'productboard.com', true),
  ('ProofHub', array['PADDLE.NET* PROOFHUB', 'PROOFHUB.COM'], 'project_management', 'proofhub.com', true),
  ('Proofpoint', array['PROOFPOINT.COM', 'PROOFPOINT INC'], 'security', 'proofpoint.com', true),
  ('Proposify', array['PROPOSIFY INC', 'PROPOSIFY.COM'], 'sales', 'proposify.com', true),
  ('ProtonMail', array['PROTON.ME', 'PROTON AG'], 'communication', 'proton.me', true),
  ('ProtoPie', array['PROTOPIE.IO', 'STUDIO XID'], 'design', 'protopie.io', true),
  ('Qualtrics', array['QUALTRICS.COM', 'QUALTRICS LLC'], 'other', 'qualtrics.com', true),
  ('Qualys', array['QUALYS.COM', 'QUALYS INC'], 'security', 'qualys.com', true),
  ('QuickBooks', array['INTUIT *QBOOKS', 'QB'], 'finance', 'quickbooks.intuit.com', true),
  ('Quire', array['QUIRE.IO', 'POTIX QUIRE'], 'project_management', 'quire.io', true),
  ('Qwilr', array['QWILR.COM'], 'sales', 'qwilr.com', true),
  ('Railway', array['RAILWAY.APP', 'RAILWAY CORP'], 'devtools', 'railway.app', true),
  ('Ramp', array['RAMP.COM', 'RAMP CARD'], 'finance', 'ramp.com', true),
  ('Rapid7', array['RAPID7.COM', 'RAPID7 INC'], 'security', 'rapid7.com', true),
  ('Re:amaze', array['PADDLE.NET* REAMAZE', 'REAMAZE.COM'], 'support', 'reamaze.com', true),
  ('Recurly', array['RECURLY.COM', 'RECURLY INC'], 'finance', 'recurly.com', true),
  ('Redmine', array['REDMINE.ORG'], 'project_management', 'redmine.org', true),
  ('Remote.com', array['REMOTE TECHNOLOGY INC', 'REMOTE GLOBAL PAYROLL'], 'hr', 'remote.com', true),
  ('Render', array['RENDER.COM', 'RENDER SERVICES INC'], 'devtools', 'render.com', true),
  ('Reply.io', array['REPLYIO', 'REPLY.IO LLC'], 'sales', 'reply.io', true),
  ('Restream', array['PADDLE.NET* RESTREAM', 'RESTREAM.IO'], 'video', 'restream.io', true),
  ('RingCentral', array['RINGCENTRAL INC', 'RC*RINGCENTRAL'], 'communication', 'ringcentral.com', true),
  ('Rippling', array['RIPPLING.COM', 'RIPPLING HR'], 'hr', 'rippling.com', true),
  ('Riverside.fm', array['PADDLE.NET* RIVERSIDE', 'RIVERSIDE FM LTD'], 'video', 'riverside.fm', true),
  ('Robin', array['ROBINPOWERED.COM', 'ROBIN POWERED INC'], 'other', 'robinpowered.com', true),
  ('Rocket.Chat', array['ROCKET CHAT INC'], 'communication', 'rocket.chat', true),
  ('RocketReach', array['ROCKETREACH.CO'], 'sales', 'rocketreach.co', true),
  ('Rollbar', array['ROLLBAR.COM', 'ROLLBAR INC'], 'observability', 'rollbar.com', true),
  ('Runn', array['RUNN.IO', 'RUNN RESOURCE'], 'project_management', 'runn.io', true),
  ('Sage Intacct', array['SAGE.COM', 'INTACCT'], 'finance', 'sageintacct.com', true),
  ('Salesflare', array['SALESFLARE.COM'], 'crm', 'salesflare.com', true),
  ('Salesforce', array['SALESFORCE.COM SFDC', 'SFDC', 'SALESFORCE INC'], 'crm', 'salesforce.com', true),
  ('Salesforce Service Cloud', array['SALESFORCE.COM', 'SFDC'], 'support', 'salesforce.com', true),
  ('Salesloft', array['SALESLOFT INC', 'SALESLOFT.COM'], 'sales', 'salesloft.com', true),
  ('Salesmate', array['SALESMATE.IO'], 'crm', 'salesmate.io', true),
  ('SAP Ariba', array['SAP*ARIBA', 'ARIBA.COM'], 'other', 'ariba.com', true),
  ('SAP Concur', array['SAP *CONCUR', 'CONCUR.COM'], 'finance', 'concur.com', true),
  ('Scoro', array['SCORO.COM', 'SCORO SOFTWARE'], 'project_management', 'scoro.com', true),
  ('ScreenFlow', array['TELESTREAM LLC', 'SCREENFLOW.COM'], 'video', 'screenflow.com', true),
  ('SE Ranking', array['SERANKING.COM'], 'marketing', 'seranking.com', true),
  ('Seamless.AI', array['SEAMLESS AI INC'], 'sales', 'seamless.ai', true),
  ('Segment', array['TWILIO*SEGMENT', 'SEGMENT.COM', 'TWILIO *SEGMENT'], 'marketing', 'segment.com', true),
  ('Semrush', array['SEMRUSH INC', 'SEMRUSH.COM'], 'marketing', 'semrush.com', true),
  ('SendGrid', array['TWILIO*SENDGRID', 'SENDGRID.COM'], 'devtools', 'sendgrid.com', true),
  ('Sendspark', array['PADDLE.NET* SENDSPARK', 'SENDSPARK.COM'], 'video', 'sendspark.com', true),
  ('SentinelOne', array['SENTINELONE.COM', 'SENTINELONE INC'], 'security', 'sentinelone.com', true),
  ('Sentry', array['SENTRY.IO', 'FUNCTIONAL SOFTWARE INC'], 'observability', 'sentry.io', true),
  ('Shippo', array['GOSHIPPO.COM', 'SHIPPO INC'], 'other', 'goshippo.com', true),
  ('ShipStation', array['SHIPSTATION.COM', 'AURACOMMERCE SHIPSTATION'], 'other', 'shipstation.com', true),
  ('Shopify', array['SHOPIFY INC', 'SHOPIFY.COM', 'SP * SHOPIFY'], 'other', 'shopify.com', true),
  ('Shortcut', array['SHORTCUT SOFTWARE INC', 'SHORTCUT.COM'], 'project_management', 'shortcut.com', true),
  ('SignEasy', array['SIGNEASY.COM'], 'sales', 'signeasy.com', true),
  ('SignNow', array['SIGNNOW.COM', 'AIRSLATE SIGNNOW', 'PADDLE.NET* SIGNNOW'], 'other', 'signnow.com', true),
  ('Similarweb', array['SIMILARWEB.COM'], 'analytics', 'similarweb.com', true),
  ('Sisense', array['SISENSE.COM', 'SISENSE INC'], 'analytics', 'sisense.com', true),
  ('Site24x7', array['ZOHO*SITE24X7'], 'observability', 'site24x7.com', true),
  ('Sketch', array['SKETCH.COM', 'SKETCH B.V.'], 'design', 'sketch.com', true),
  ('Skype', array['MSFT *SKYPE', 'SKYPE.COM'], 'communication', 'skype.com', true),
  ('Slack', array['SLACK T-XXXX', 'SLACK TECHNOLOGIES', 'SLACK.COM'], 'communication', 'slack.com', true),
  ('Slite', array['SLITE.COM', 'SLITE INC'], 'productivity', 'slite.com', true),
  ('Smartling', array['SMARTLING.COM', 'SMARTLING INC'], 'other', 'smartling.com', true),
  ('SmartRecruiters', array['SMARTRECRUITERS.COM'], 'hr', 'smartrecruiters.com', true),
  ('Smartsheet', array['SMARTSHEET.COM', 'SMARTSHEET INC'], 'productivity', 'smartsheet.com', true),
  ('Snyk', array['SNYK.IO', 'SNYK LTD'], 'security', 'snyk.io', true),
  ('Sophos', array['SOPHOS.COM', 'SOPHOS LTD'], 'security', 'sophos.com', true),
  ('Spendesk', array['SPENDESK.COM', 'SPENDESK CARD'], 'finance', 'spendesk.com', true),
  ('Spiceworks', array['SPICEWORKS.COM', 'SPICEWORKS INC'], 'support', 'spiceworks.com', true),
  ('Spline', array['SPLINE.DESIGN', 'SPLINE SYSTEMS'], 'design', 'spline.design', true),
  ('Splunk', array['SPLUNK.COM', 'SPLUNK INC'], 'observability', 'splunk.com', true),
  ('Sprout Social', array['SPROUT SOCIAL INC', 'SPROUTSOCIAL.COM'], 'marketing', 'sproutsocial.com', true),
  ('Squadcast', array['SQUADCAST.COM'], 'observability', 'squadcast.com', true),
  ('Squarespace', array['SQSP *SQUARESPACE', 'SQUARESPACE INC'], 'marketing', 'squarespace.com', true),
  ('Statuspage', array['ATLASSIAN*STATUSPAGE', 'STATUSPAGE.IO'], 'observability', 'statuspage.io', true),
  ('Streak', array['STREAK.COM', 'STREAK CRM'], 'crm', 'streak.com', true),
  ('StreamYard', array['PADDLE.NET* STREAMYARD', 'STREAMYARD.COM'], 'video', 'streamyard.com', true),
  ('Stripe', array['STRIPE.COM', 'STRIPE BILLING'], 'finance', 'stripe.com', true),
  ('SugarCRM', array['SUGARCRM INC', 'SUGAR CRM'], 'crm', 'sugarcrm.com', true),
  ('Sumo Logic', array['SUMO LOGIC INC', 'SUMOLOGIC.COM'], 'observability', 'sumologic.com', true),
  ('Supabase', array['SUPABASE.COM', 'SUPABASE INC'], 'devtools', 'supabase.com', true),
  ('Superhuman', array['SUPERHUMAN.COM', 'SUPERHUMAN LABS'], 'communication', 'superhuman.com', true),
  ('SupportBee', array['PADDLE.NET* SUPPORTBEE', 'SUPPORTBEE.COM'], 'support', 'supportbee.com', true),
  ('SurveyMonkey', array['SVMK *SURVEYMONKEY', 'MOMENTIVE INC'], 'marketing', 'surveymonkey.com', true),
  ('Synthesia', array['SYNTHESIA LTD', 'SYNTHESIA.IO'], 'video', 'synthesia.io', true),
  ('SysAid', array['SYSAID.COM', 'SYSAID TECHNOLOGIES'], 'support', 'sysaid.com', true),
  ('Tableau', array['SALESFORCE*TABLEAU', 'TABLEAU SOFTWARE'], 'analytics', 'tableau.com', true),
  ('TalentLMS', array['TALENTLMS.COM', 'EPIGNOSIS TALENTLMS'], 'other', 'talentlms.com', true),
  ('Targetprocess', array['APPTIO INC', 'TARGETPROCESS.COM'], 'project_management', 'targetprocess.com', true),
  ('Taskade', array['TASKADE.COM', 'TASKADE INC'], 'project_management', 'taskade.com', true),
  ('Tawk.to', '{}', 'support', 'tawk.to', true),
  ('Teamwork', array['TEAMWORK.COM', 'TEAMWORK CRM LTD'], 'project_management', 'teamwork.com', true),
  ('Tenable', array['TENABLE.COM', 'TENABLE NETWORK SECURITY'], 'security', 'tenable.com', true),
  ('Terraform Cloud', array['HASHICORP*TERRAFORM', 'TF'], 'devtools', 'terraform.io', true),
  ('Tidio', array['PADDLE.NET* TIDIO', 'TIDIO LLC', 'TIDIO.COM'], 'support', 'tidio.com', true),
  ('Tipalti', array['TIPALTI.COM', 'TIPALTI INC'], 'finance', 'tipalti.com', true),
  ('Todoist', array['TODOIST.COM', 'DOIST INC'], 'productivity', 'todoist.com', true),
  ('Toggl Plan', array['TOGGL OU', 'TOGGL.COM'], 'project_management', 'toggl.com', true),
  ('Toggl Track', array['TOGGL.COM', 'TOGGL OU'], 'productivity', 'toggl.com', true),
  ('Tradeshift', array['TRADESHIFT INC', 'TRADESHIFT.COM'], 'other', 'tradeshift.com', true),
  ('Travis CI', array['TRAVIS-CI.COM', 'TRAVISCI'], 'devtools', 'travis-ci.com', true),
  ('Trello', array['ATLASSIAN*TRELLO', 'TRELLO.COM', 'ATLASSIAN'], 'productivity', 'trello.com', true),
  ('Trend Micro', array['TRENDMICRO.COM', 'TREND MICRO INC'], 'security', 'trendmicro.com', true),
  ('TriNet', array['TRINET.COM', 'TRINET PEO'], 'hr', 'trinet.com', true),
  ('Twilio', array['TWILIO.COM', 'TWILIO INC'], 'communication', 'twilio.com', true),
  ('Twingate', array['TWINGATE.COM', 'TWINGATE INC'], 'security', 'twingate.com', true),
  ('Typeform', array['FS *TYPEFORM', 'TYPEFORM SL'], 'marketing', 'typeform.com', true),
  ('UKG', array['UKG.COM', 'ULTIMATE KRONOS GRP'], 'hr', 'ukg.com', true),
  ('Unbounce', array['UNBOUNCE.COM', 'UNBOUNCE MARKETING'], 'marketing', 'unbounce.com', true),
  ('Unsplash', array['UNSPLASH INC', 'UNSPLASH+'], 'design', 'unsplash.com', true),
  ('UptimeRobot', array['UPTIMEROBOT.COM'], 'observability', 'uptimerobot.com', true),
  ('UserVoice', array['USERVOICE INC', 'USERVOICE.COM'], 'support', 'uservoice.com', true),
  ('UXPin', array['UXPIN.COM', 'UXPIN INC'], 'design', 'uxpin.com', true),
  ('Vanta', array['VANTA.COM', 'VANTA INC'], 'security', 'vanta.com', true),
  ('Veed', array['PADDLE.NET* VEED', 'VEED.IO'], 'video', 'veed.io', true),
  ('Vendr', array['VENDR.COM', 'VENDR INC'], 'finance', 'vendr.com', true),
  ('Vercel', array['VERCEL INC', 'VERCEL.COM'], 'devtools', 'vercel.com', true),
  ('Vidcast', array['VIDCAST BY SENDSPARK'], 'video', 'sendspark.com', true),
  ('Vidyard', array['VIDYARD INC', 'VIDYARD.COM'], 'sales', 'vidyard.com', true),
  ('Vimeo', array['VIMEO.COM', 'VIMEO INC'], 'video', 'vimeo.com', true),
  ('Vonage', array['VONAGE.COM', 'VONAGE AMERICA'], 'communication', 'vonage.com', true),
  ('Vouch', array['VOUCH INSURANCE', 'VOUCH.US'], 'other', 'vouch.us', true),
  ('Vtiger CRM', array['VTIGER', 'VTIGER.COM'], 'crm', 'vtiger.com', true),
  ('VWO', array['WINGIFY SOFTWARE', 'VWO.COM'], 'marketing', 'vwo.com', true),
  ('Vyond', array['VYOND INC', 'VYOND.COM'], 'video', 'vyond.com', true),
  ('Wave', array['WAVEAPPS.COM', 'WAVE ACCOUNTING'], 'finance', 'waveapps.com', true),
  ('Webex', array['CISCO WEBEX', 'WEBEX.COM'], 'communication', 'webex.com', true),
  ('Webflow', array['WEBFLOW INC', 'WEBFLOW.COM'], 'marketing', 'webflow.com', true),
  ('Weebly', array['WEEBLY.COM', 'SQUARE WEEBLY'], 'other', 'weebly.com', true),
  ('WhatsApp Business', array['META*WHATSAPP'], 'communication', 'whatsapp.com', true),
  ('When I Work', array['WHENIWORK.COM', 'WIW'], 'hr', 'wheniwork.com', true),
  ('Whereby', array['WHEREBY AS', 'WHEREBY.COM'], 'video', 'whereby.com', true),
  ('Wirecast', array['WIRECAST.COM'], 'video', 'wirecast.com', true),
  ('Wise', array['WISE.COM', 'TRANSFERWISE'], 'finance', 'wise.com', true),
  ('Wistia', array['WISTIA INC', 'WISTIA.COM'], 'video', 'wistia.com', true),
  ('Wix', array['WIX.COM*PREMIUM', 'WIX INC'], 'marketing', 'wix.com', true),
  ('Wiz', array['WIZ.IO', 'WIZ INC'], 'security', 'wiz.io', true),
  ('WooCommerce', array['WOOCOMMERCE.COM', 'AUTOMATTIC WOO'], 'other', 'woocommerce.com', true),
  ('Woopra', array['WOOPRA.COM'], 'analytics', 'woopra.com', true),
  ('WordPress.com', array['AUTOMATTIC WORDPRESS', 'WORDPRESS.COM INC'], 'other', 'wordpress.com', true),
  ('Workable', array['WORKABLE.COM', 'WORKABLE ATS'], 'hr', 'workable.com', true),
  ('Workato', array['WORKATO.COM', 'WORKATO INC'], 'other', 'workato.com', true),
  ('Workbooks CRM', array['WORKBOOKS.COM'], 'crm', 'workbooks.com', true),
  ('Workday', array['WORKDAY INC', 'WDAY'], 'hr', 'workday.com', true),
  ('Workfront', array['ADOBE INC', 'WORKFRONT.COM'], 'project_management', 'workfront.com', true),
  ('Wrike', array['WRIKE.COM', 'WRIKE INC'], 'productivity', 'wrike.com', true),
  ('Xactly', array['XACTLY CORP'], 'sales', 'xactlycorp.com', true),
  ('Xero', array['XERO.COM', 'XERO ACCOUNTING'], 'finance', 'xero.com', true),
  ('Yesware', array['YESWARE INC', 'YESWARE.COM'], 'sales', 'yesware.com', true),
  ('Yoast SEO', array['YOAST.COM', 'TEAM YOAST'], 'marketing', 'yoast.com', true),
  ('Zapier', array['ZAPIER.COM', 'ZAPIER INC'], 'productivity', 'zapier.com', true),
  ('Zendesk', array['ZENDESK INC', 'ZENDESK.COM', 'ZD'], 'communication', 'zendesk.com', true),
  ('Zendesk Sell', array['ZENDESK INC', 'ZENDESK*SELL'], 'crm', 'zendesk.com', true),
  ('Zenefits', array['ZENEFITS.COM', 'TRINET ZENEFITS'], 'hr', 'zenefits.com', true),
  ('Zenkit', array['ZENKIT.COM', 'AXONIC ZENKIT'], 'project_management', 'zenkit.com', true),
  ('Zeplin', array['ZEPLIN.IO', 'ZEPLIN INC'], 'design', 'zeplin.io', true),
  ('Zip', array['ZIP HQ INC', 'ZIPHQ.COM'], 'other', 'ziphq.com', true),
  ('Zoho Bigin', array['ZOHO CORP', 'BIGIN BY ZOHO'], 'crm', 'bigin.zoho.com', true),
  ('Zoho Books', array['ZOHO *BOOKS', 'ZOHOBOOKS'], 'finance', 'zoho.com', true),
  ('Zoho CRM', array['ZOHO CORP', 'ZOHO.COM', 'ZOHO CRM PLUS'], 'crm', 'zoho.com', true),
  ('Zoho Desk', array['ZOHO CORP'], 'support', 'desk.zoho.com', true),
  ('Zoho Projects', array['ZOHO CORP'], 'project_management', 'projects.zoho.com', true),
  ('Zoho SalesIQ', array['ZOHO CORP'], 'support', 'salesiq.zoho.com', true),
  ('Zoom', array['ZOOM.US', 'ZOOM VIDEO COMMUNICATIONS'], 'communication', 'zoom.us', true),
  ('ZoomInfo', array['ZOOMINFO TECH', 'ZI*ZOOMINFO'], 'sales', 'zoominfo.com', true),
  ('Zscaler', array['ZSCALER.COM', 'ZSCALER INC'], 'security', 'zscaler.com', true)
on conflict (lower(name)) do nothing;
